hosts:
  staging:
    stage: staging
    hostname: [PROJECT_CODE_HERE].ssh.statik.be
    remote_user: [PROJECT_CODE_HERE]livestatikbe
    deploy_path: ~/subsites/[PROJECT_CODE_HERE].staging.statik.be
    http_user: [PROJECT_CODE_HERE]livestatikbe
    htaccess_file: htaccess-staging
    robots_file: robots-staging
    configFile: ~/.ssh/config
    http_host: [PROJECT_CODE_HERE].staging.statik.be
  production:
    stage: production
    hostname: [PROJECT_CODE_HERE].ssh.statik.be
    remote_user: [PROJECT_CODE_HERE]livestatikbe
    deploy_path: ~/subsites/[PROJECT_CODE_HERE].live.statik.be
    http_user: [PROJECT_CODE_HERE]livestatikbe
    htaccess_file: htaccess-production
    robots_file: robots-production
    configFile: ~/.ssh/config
    http_host: [PROJECT_CODE_HERE].live.statik.be
