field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
fieldLayouts:
  b99f4595-d28c-453a-86c2-db4f82eaf870:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 71a7d521-3217-4254-8b3f-f778279d342c # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9479f718-c556-48b4-8306-3ab6b6ecb19c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fa3e75a-c69d-4482-9083-e416986b4788 # Table
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00a9d157-2549-4db2-804e-580e8a8eb8b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ecee8ded-a8fe-4ff9-b68a-a9abb32d3a76
        userCondition: null
fields:
  8fa3e75a-c69d-4482-9083-e416986b4788: # Table
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: table
    instructions: null
    name: Table
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Table.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  71a7d521-3217-4254-8b3f-f778279d342c: # Title
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blockTitle
    instructions: null
    name: Title
    searchable: true
    settings:
      someAttribute: null
    translationKeyFormat: null
    translationMethod: site
    type: modules\statik\fields\AnchorLink
handle: customTable
name: 'Custom Table'
sortOrder: 9
