field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
fieldLayouts:
  9334ab5d-2a5e-48de-8e2b-f9473c1d7ffb:
    tabs:
      -
        elements:
          -
            fieldUid: 4769bfc3-3064-404b-baa5-1bd5c5ff2acf # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9b825b00-aa1c-4ad2-b013-e29ee855e551 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 74a30650-eb90-462f-a104-de1d41ac8221 # Form
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ae73d04c-119e-4cc7-a3fc-bf41d36c5510 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9b825b00-aa1c-4ad2-b013-e29ee855e551: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Type your text here.'
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  74a30650-eb90-462f-a104-de1d41ac8221: # Form
    contentColumnType: integer
    fieldGroup: null
    handle: form
    instructions: 'Select a form in the list below to appear in this block.'
    name: Form
    searchable: true
    translationKeyFormat: null
    translationMethod: site
    type: Solspace\Freeform\FieldTypes\FormFieldType
  4769bfc3-3064-404b-baa5-1bd5c5ff2acf: # Title
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Type an optional title to appear with the form.'
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  ae73d04c-119e-4cc7-a3fc-bf41d36c5510: # Background Color
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Select the background color of the whole section. Note: depending on the background color, the text colors might change.'
    name: 'Background Color'
    searchable: true
    settings:
      dataSet: 'Background colors'
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
handle: form
name: Form
sortOrder: 7
