field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
fieldLayouts:
  dbac7280-eb96-48c9-9218-1f8706af3656:
    tabs:
      -
        elements:
          -
            fieldUid: cd736fb3-c9b7-4ce1-88a8-da8b64249eb1 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 683cbd88-ef11-45e0-83b4-e20d03f6ea6b # Image width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 9abed6d9-3042-4dd4-add0-3115a6e2693b # Image position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 4ce05044-aa3d-4bbe-ad21-be03fbc1a273 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 9084b802-1468-4763-a867-2e4b1ebd3f09 # Show larger version in popup
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  4ce05044-aa3d-4bbe-ad21-be03fbc1a273: # Background Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Select the background color of the whole section.'
    name: 'Background Color'
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  9abed6d9-3042-4dd4-add0-3115a6e2693b: # Image position
    columnSuffix: vwktiheg
    contentColumnType: string
    fieldGroup: null
    handle: imagePosition
    instructions: ''
    name: 'Image position'
    searchable: false
    settings:
      default: center
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  683cbd88-ef11-45e0-83b4-e20d03f6ea6b: # Image width
    columnSuffix: xbqglaie
    contentColumnType: string
    fieldGroup: null
    handle: imageWidth
    instructions: ''
    name: 'Image width'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - full
            -
              - value
              - full
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 1/2
            -
              - value
              - half
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 1/3
            -
              - value
              - oneThird
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 1/4
            -
              - value
              - oneFourth
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  9084b802-1468-4763-a867-2e4b1ebd3f09: # Show larger version in popup
    columnSuffix: xmzvkqux
    contentColumnType: boolean
    fieldGroup: null
    handle: showLargerVersionInPopup
    instructions: ''
    name: 'Show larger version in popup'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  cd736fb3-c9b7-4ce1-88a8-da8b64249eb1: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'The minimum with for this image is 1200px. The ideal width is 2400px'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 3
