field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
fieldLayouts:
  0b203f95-b680-4192-8ebc-fd84ef05fc3c:
    tabs:
      -
        elements:
          -
            fieldUid: e6665f06-bacd-4421-bd2e-cdf693c23eaf # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 776fa716-10bb-48bb-ae08-28870f9d77e7 # Entries
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4389ba83-8e69-4edb-b3c3-ca0ba89617c1 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  776fa716-10bb-48bb-ae08-28870f9d77e7: # Entries
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: 'Select entries  to display in this overview'
    name: Entries
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: true
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  4389ba83-8e69-4edb-b3c3-ca0ba89617c1: # Background Color
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Select the background color of the whole section. Note: depending on the background color, the text colors might change.'
    name: 'Background Color'
    searchable: true
    settings:
      dataSet: 'Background colors'
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  e6665f06-bacd-4421-bd2e-cdf693c23eaf: # Title
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: 'Add an optional title to the block'
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: overview
name: Overview
sortOrder: 8
