field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
fieldLayouts:
  f4023492-353e-4a86-9695-455793644dc4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1a9703c9-1eb8-4b3a-94e1-1386e5b24f2a # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc1db95c-60f0-4911-8c01-fbd89b5f9a06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b8bf7de4-8025-4da7-9040-09ec8b731016 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05aa0d0e-b0b6-4161-a302-d52aa0e73032
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ca8bb389-d0f3-4dbb-af40-e2f6ef211040 # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6f1bc45-4a68-4a62-b22d-014547a0e11d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f21594e6-d83e-4047-a36c-0d6b709719e1 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed69e655-73d9-4f2b-94a0-2275e9b4faf8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40e14f90-0640-452d-9c8a-9f30f73bacbb # Image position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e11cb59-1985-4f62-8da1-4c8694b813fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bd732ee5-59bb-41a5-81e1-b0de29ca7146 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ed3a959-a53c-497c-8838-852a96e2c278
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3cac461-fd7a-4f9a-8486-520f99041b3f
        userCondition: null
fields:
  1a9703c9-1eb8-4b3a-94e1-1386e5b24f2a: # Title
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blockTitle
    instructions: 'Add an optional title to the block'
    name: Title
    searchable: true
    settings:
      someAttribute: null
    translationKeyFormat: null
    translationMethod: site
    type: modules\statik\fields\AnchorLink
  40e14f90-0640-452d-9c8a-9f30f73bacbb: # Image position
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: 'Select the position of the image in relation to the text block.'
    name: 'Image position'
    searchable: false
    settings:
      default: left
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - ''
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  b8bf7de4-8025-4da7-9040-09ec8b731016: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Type your text here'
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 25f93ead-d3f6-4049-ba98-6378754f4289 # Extended
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\ckeditor\Field
  bd732ee5-59bb-41a5-81e1-b0de29ca7146: # Background Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Select the background color of the whole section. Note: depending on the background color, the text colors might change.'
    name: 'Background Color'
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  ca8bb389-d0f3-4dbb-af40-e2f6ef211040: # Call to action
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cta
    instructions: 'Add one or more call to actions and define styling (button, link, ...).'
    name: 'Call to action'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1114632954
      columns:
        __assoc__:
          -
            - 97e1c649-ce58-4388-bbc1-1f4e41d938b6 # Link
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_7_cta}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a call to action'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  f21594e6-d83e-4047-a36c-0d6b709719e1: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'The minimum width for this image is 660px. The ideal width is 1320px.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: textImage
name: 'Text (+ Image)'
sortOrder: 1
