field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
fieldLayouts:
  4bb37325-4657-4b4b-a37d-a9601263cf72:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d66ffcef-8ccc-4e89-9e36-bce49e0dd17a # Video
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10b5c1ef-5a1d-4b4f-90ca-41388b1bc2d1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 724561c2-845a-427f-b005-e0c2a35e0112 # Placeholder Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b84cf6f5-a37f-4a41-8908-4157a510c99d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fca40313-aa0d-4206-a530-c638a5166f69 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee4947c6-1e36-4c0a-9f92-995d187c1983
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ae5f2b18-f88e-4521-a729-d5fccff56993 # Video Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cf136e3-1af6-43c5-bcd3-2d6cf2878c1c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 1b44f4cf-c6f3-495e-b01a-3cb36749abfd
        userCondition: null
fields:
  724561c2-845a-427f-b005-e0c2a35e0112: # Placeholder Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: placeholderImage
    instructions: null
    name: 'Placeholder Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Public Files
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Public Files
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ae5f2b18-f88e-4521-a729-d5fccff56993: # Video Caption
    columnSuffix: tetgykfj
    contentColumnType: text
    fieldGroup: null
    handle: videoCaption
    instructions: null
    name: 'Video Caption'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 7d23b02c-ad1d-44a8-9751-35fbdcc38963 # Standard
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  d66ffcef-8ccc-4e89-9e36-bce49e0dd17a: # Video
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: video
    instructions: 'Paste the URL of a YouTube or Vimeo video. '
    name: Video
    searchable: true
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
  fca40313-aa0d-4206-a530-c638a5166f69: # Background Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Select the background color of the whole section.'
    name: 'Background Color'
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
handle: video
name: Video
sortOrder: 4
