data:
  dataRetention: years
  dataRetentionValue: '2'
  fileUploadsAction: retain
  notifications:
    -
      attachAssets: null
      attachFiles: true
      attachPdf: ''
      bcc: null
      cc: null
      conditions:
        conditionRule: all
        sendRule: send
      content: '[{"type":"paragraph","content":[{"type":"text","text":"Onderstaand bericht werd ontvangen op "},{"type":"variableTag","attrs":{"label":"Timestamp (yyyy-mm-dd hh:mm:ss)","value":"{timestamp}"}},{"type":"text","text":":"}]},{"type":"paragraph","content":[{"type":"variableTag","attrs":{"label":"All Form Fields","value":"{allFields}"}}]}]'
      enableConditions: false
      enabled: true
      formId: null
      from: '{systemEmail}'
      fromName: '{systemName}'
      id: stencilR446Bz7gghBJtnzG
      name: 'Admin Notification NL'
      pdfTemplateId: null
      recipients: email
      replyTo: '{field.emailAddress}'
      replyToName: null
      sender: null
      subject: 'Nieuw contact bericht op " {formName} "'
      templateId: 1
      to: '{systemReplyTo}'
      uid: null
    -
      attachAssets: null
      attachFiles: true
      attachPdf: ''
      bcc: null
      cc: null
      conditions:
        conditionRule: all
        sendRule: send
      content: '[{"type":"paragraph","content":[{"type":"text","text":"We hebben onderstaand bericht van je ontvangen, hierop proberen wij zo snel mogelijk te antwoorden."}]},{"type":"paragraph","content":[{"type":"variableTag","attrs":{"label":"All Form Fields","value":"{allFields}"}}]}]'
      enableConditions: false
      enabled: true
      formId: null
      from: '{systemEmail}'
      fromName: '{systemName}'
      id: stencilzSILwMJq7PZwFtYI
      name: 'User Notification NL'
      pdfTemplateId: null
      recipients: email
      replyTo: '{systemReplyTo}'
      replyToName: null
      sender: null
      subject: 'Bedankt voor je bericht'
      templateId: 1
      to: '{field.emailAddress}'
      uid: null
  pages:
    -
      id: new1272610411
      label: 'Page 1'
      notificationFlag: true
      rows:
        -
          fields:
            -
              brandNewField: false
              columnWidth: 12
              handle: yourName
              hasLabel: true
              id: new7715-7348
              label: 'Your Name'
              settings:
                firstNameCollapsed: false
                firstNameDefaultValue: ''
                firstNameEnabled: true
                firstNameLabel: Voornaam
                firstNamePlaceholder: ''
                firstNameRequired: true
                handle: yourName
                instructions: ''
                instructionsPosition: ''
                label: 'Your Name'
                labelPosition: verbb\formie\positions\Hidden
                lastNameCollapsed: false
                lastNameDefaultValue: ''
                lastNameEnabled: true
                lastNameLabel: Achternaam
                lastNamePlaceholder: ''
                lastNameRequired: true
                limitType: characters
                middleNameCollapsed: true
                middleNameDefaultValue: ''
                middleNameEnabled: false
                middleNameLabel: 'Middle Name'
                placeholder: 'Your name'
                prefixCollapsed: true
                prefixDefaultValue: ''
                prefixEnabled: false
                prefixLabel: Prefix
                subfieldLabelPosition: ''
                useMultipleFields: true
                visibility: ''
              type: verbb\formie\fields\formfields\Name
              vid: new4757-9668
          id: new8990-9934
        -
          fields:
            -
              brandNewField: false
              columnWidth: 12
              handle: emailAddress
              hasLabel: true
              id: new6482-9528
              label: E-mail
              settings:
                handle: emailAddress
                instructions: ''
                instructionsPosition: ''
                label: E-mail
                labelPosition: ''
                limitType: characters
                placeholder: ''
                required: true
                visibility: ''
              type: verbb\formie\fields\formfields\Email
              vid: new8388-8030
          id: new9524-8509
        -
          fields:
            -
              brandNewField: false
              columnWidth: 12
              handle: message
              hasLabel: true
              id: new982-7322
              label: Bericht
              settings:
                handle: message
                instructions: ''
                instructionsPosition: ''
                label: Bericht
                labelPosition: ''
                limitType: characters
                placeholder: ''
                required: true
                visibility: ''
              type: verbb\formie\fields\formfields\MultiLineText
              vid: new9480-2888
          id: new2177-9685
        -
          fields:
            -
              brandNewField: false
              columnWidth: 12
              handle: privacy
              hasLabel: true
              id: new1557664881
              isNested: false
              label: privacy
              settings:
                checkedValue: 'Yes'
                defaultValue: false
                description: '[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Ik verklaar dat ik de "},{"type":"text","marks":[{"type":"link","attrs":{"href":"https://craft.live.statik.be/nl/privacy#entry:814@1","target":"_blank","class":null}}],"text":"privacy policy"},{"type":"text","text":" heb gelezen en goedgekeurd."}]}]'
                handle: privacy
                instructionsPosition: ''
                label: privacy
                labelPosition: verbb\formie\positions\Hidden
                required: true
                uncheckedValue: 'No'
              type: verbb\formie\fields\formfields\Agree
              vid: new4253-2904
          id: new4676-559
      settings:
        backButtonLabel: Back
        buttonsPosition: left
        label: 'Page 1'
        showBackButton: false
        submitButtonLabel: 'Contacteer ons'
      sortOrder: 0
  settings:
    collectIp: false
    collectUser: false
    dataRetention: null
    dataRetentionValue: null
    defaultEmailTemplateId: '1'
    defaultInstructionsPosition: verbb\formie\positions\BelowInput
    defaultLabelPosition: verbb\formie\positions\AboveInput
    disableCaptchas: false
    displayCurrentPageTitle: false
    displayFormTitle: false
    displayPageProgress: false
    displayPageTabs: false
    errorMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Couldn’t save submission due to errors."}]}]'
    errorMessagePosition: top-form
    fileUploadsAction: null
    integrations:
      honeypot:
        enabled: '1'
        showAllPages: ''
      javascript:
        enabled: ''
        showAllPages: ''
    limitSubmissions: false
    limitSubmissionsMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    limitSubmissionsNumber: null
    limitSubmissionsType: total
    loadingIndicator: spinner
    loadingIndicatorText: null
    progressPosition: end
    redirectUrl: null
    requireUser: false
    requireUserMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    scheduleForm: false
    scheduleFormEnd: null
    scheduleFormExpiredMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    scheduleFormPendingMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    scheduleFormStart: null
    scrollToTop: true
    submissionTitleFormat: '{field.emailAddress}-{timestamp}'
    submitAction: entry
    submitActionFormHide: false
    submitActionMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Thank you for contacting us! Our team will get in touch shortly to follow up on your message."}]}]'
    submitActionMessagePosition: top-form
    submitActionMessageTimeout: null
    submitActionTab: same-tab
    submitActionUrl: null
    submitMethod: page-reload
    validationOnFocus: true
    validationOnSubmit: true
  userDeletedAction: retain
defaultStatus: c9d6819e-8ea5-4d16-91de-4c691d11b42d # New
handle: contactForm
name: 'Contact Form'
submitActionEntry: null
template: 2fc9314d-a36d-4952-bc62-530aed9da924 # Statik
