color: null
fieldLayouts:
  f997fbbd-3d0f-4ed7-adc1-ba30da763d82:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e2e2a303-7d29-4edb-846d-84e6c8494c50
            handle: null
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70237f92-d5cd-452c-9c10-ea46b8336b13
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 655b59ef-5329-40e5-9a85-6ea2ac1d8a14
            handle: null
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da847db5-850e-4d05-bb3a-e5803c3e04ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7def856e-47b3-4b83-ba43-23b5da28a176
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05216db1-92ad-4acb-ad4a-caf5abad6e04
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: df7389a1-233e-4f41-8340-9d16eee18c51
            handle: null
            includeInCards: false
            instructions: null
            label: CTA
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7509d04b-802c-4197-92f3-60e6ee71746e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac60331a-e9bd-4399-8b44-42a2c469fd52
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f1b736f-d51f-4b43-93cd-059bdcda13b3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ebeecdff-5e28-44c3-8233-ca59e850eb04
        userCondition: null
handle: callToAction
hasTitleField: false
icon: null
name: 'Call To Action'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
