fieldLayouts:
  477674b4-58e0-476e-9644-82d2e9acf19d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0f4d5200-5a69-45f0-a598-d6c6e89dadd9
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d810011f-cd8a-4d88-bf89-3b5cdb39b556
            warning: null
            width: 100
        name: Content
        uid: 7d3c8ba5-ffdb-41cf-b371-a8dfb757ed4a
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2351b1e5-f35b-4944-8ebe-39d5b4911703
            warning: null
            width: 100
        name: SEO
        uid: bb531ad4-f823-4fc7-b7f9-ebb082573da0
handle: confirmAccount
hasTitleField: true
name: 'Confirm your account'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
