fieldLayouts:
  c015e9cc-e735-4ef0-b2d1-61c64f6acd9f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3e2218c5-12da-4afe-879a-c920fd83c4cd
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 823f6fdf-7fa6-456e-981b-f9c7238ef807
            warning: null
            width: 100
        name: Content
        uid: 91f8d13b-53f1-4def-b27c-ffb584d04737
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f1144bd-2ee7-40af-a826-ff1c0382196d
            warning: null
            width: 100
        name: SEO
        uid: 65400529-152e-45d6-b6e9-14f030721122
handle: forgotPassword
hasTitleField: true
name: 'Forgot password'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
