color: null
fieldLayouts:
  9334ab5d-2a5e-48de-8e2b-f9473c1d7ffb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4769bfc3-3064-404b-baa5-1bd5c5ff2acf
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ceea9b40-c972-44ed-9a78-13e297b373d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b825b00-aa1c-4ad2-b013-e29ee855e551
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 061635db-57d8-499f-8247-683051ee2000
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74a30650-eb90-462f-a104-de1d41ac8221
            handle: null
            includeInCards: false
            instructions: null
            label: Form
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d82ff4e9-a339-4dc7-993a-33ddbc7770e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae73d04c-119e-4cc7-a3fc-bf41d36c5510
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed5937b6-3da0-49f4-a479-17835510d6e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93748cb1-718c-4f6b-bf7f-2905cce71126
        userCondition: null
handle: form
hasTitleField: false
icon: null
name: Form
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
