color: green
fieldLayouts:
  dbac7280-eb96-48c9-9218-1f8706af3656:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 394d2e77-8303-4ce3-a456-39fcbb0c4b9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd736fb3-c9b7-4ce1-88a8-da8b64249eb1
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: baa9eb81-3124-4edd-8cfd-8a294e0b0c16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: cd736fb3-c9b7-4ce1-88a8-da8b64249eb1
                  layoutElementUid: baa9eb81-3124-4edd-8cfd-8a294e0b0c16
                  operator: notempty
                  uid: 5fe86e5b-39d5-4829-a19a-81ffd7422257
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 683cbd88-ef11-45e0-83b4-e20d03f6ea6b
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e4f5ff-7dc0-4e82-b00c-8bea4e6b9b70
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: cd736fb3-c9b7-4ce1-88a8-da8b64249eb1
                  layoutElementUid: baa9eb81-3124-4edd-8cfd-8a294e0b0c16
                  operator: notempty
                  uid: 4fe12c4e-1538-4e6b-97d4-0c4038eea43c
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 9abed6d9-3042-4dd4-add0-3115a6e2693b
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5703cb2e-6333-45b2-b5b8-78da1173aca7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: cd736fb3-c9b7-4ce1-88a8-da8b64249eb1
                  layoutElementUid: baa9eb81-3124-4edd-8cfd-8a294e0b0c16
                  operator: notempty
                  uid: de08ac12-f353-4bfd-a93e-82f199ea39e5
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 9084b802-1468-4763-a867-2e4b1ebd3f09
            handle: null
            includeInCards: true
            instructions: null
            label: 'Show larger version in popup'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: feb576a2-753f-4c0e-bc99-499d303293d5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: cd736fb3-c9b7-4ce1-88a8-da8b64249eb1
                  layoutElementUid: baa9eb81-3124-4edd-8cfd-8a294e0b0c16
                  operator: notempty
                  uid: 46d0d027-b2b7-453f-b3d5-ccabb606ef7e
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 4ce05044-aa3d-4bbe-ad21-be03fbc1a273
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccae05e3-e8e4-4417-a452-ae31afa6664d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: f986a838-979a-4945-abe0-cd3c6cbad150
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
