color: null
fieldLayouts:
  dbac7280-eb96-48c9-9218-1f8706af3656:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cd736fb3-c9b7-4ce1-88a8-da8b64249eb1
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: baa9eb81-3124-4edd-8cfd-8a294e0b0c16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 683cbd88-ef11-45e0-83b4-e20d03f6ea6b
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e4f5ff-7dc0-4e82-b00c-8bea4e6b9b70
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9abed6d9-3042-4dd4-add0-3115a6e2693b
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5703cb2e-6333-45b2-b5b8-78da1173aca7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4ce05044-aa3d-4bbe-ad21-be03fbc1a273
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccae05e3-e8e4-4417-a452-ae31afa6664d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9084b802-1468-4763-a867-2e4b1ebd3f09
            handle: null
            includeInCards: true
            instructions: null
            label: 'Show larger version in popup'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: feb576a2-753f-4c0e-bc99-499d303293d5
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: f986a838-979a-4945-abe0-cd3c6cbad150
        userCondition: null
handle: image
hasTitleField: false
icon: null
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
