fieldLayouts:
  828a0866-584e-4390-bf58-01a51969cdb2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c538a919-c992-4f5a-aa1c-beea7b01642d
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17ef52e0-a400-4016-b17b-f1c8f704646b
            warning: null
            width: 100
        name: Content
        uid: 43f6d522-2a07-4ffc-bafe-b85d3c8c5ce3
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99f8fd4e-d0b5-4dc2-8311-ad0e6e1d9ea1
            warning: null
            width: 100
        name: SEO
        uid: cc53839f-abe0-4012-b614-7453309f6098
handle: login
hasTitleField: true
name: Login
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
