color: null
fieldLayouts:
  0b203f95-b680-4192-8ebc-fd84ef05fc3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e6665f06-bacd-4421-bd2e-cdf693c23eaf
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7c5b6c1-2df2-47a9-9590-8e8c57d48212
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 776fa716-10bb-48bb-ae08-28870f9d77e7
            handle: null
            includeInCards: true
            instructions: null
            label: Entries
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76be8a95-7f6d-46e0-a7ad-0105ea2dc848
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4389ba83-8e69-4edb-b3c3-ca0ba89617c1
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3879b5f6-1d82-4b0d-a1ed-389e9ada1de2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17a9de58-71d7-452f-a480-1439982cf48e
        userCondition: null
handle: overview
hasTitleField: false
icon: null
name: Overview
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
