fieldLayouts:
  6b7fadb8-b880-45cc-b5af-2f8dbd770ab0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d217be10-f0a3-4498-829a-aaa50aee8b63
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 223acace-cdae-4ed7-9394-f825da789ada
            warning: null
            width: 100
          -
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af77011a-d451-4c28-b747-0c06fd6aa566
            warning: null
            width: 100
        name: Content
        uid: 0861d6c4-ecca-44c7-98b7-90d3e07a3a29
      -
        elements:
          -
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcb7f29c-2df1-401b-88a6-2cee29686db1
            warning: null
            width: 100
          -
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c01c3f9-00b5-46ae-9ca5-3069167abeff
            warning: null
            width: 100
          -
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b67a65a8-5261-46a5-8f60-6dbedf6640b5
            warning: null
            width: 100
        name: Overview
        uid: ff651b09-8915-4ded-bb8c-307ca5666c25
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8710a1c-d8e4-4556-987e-14da4429c8ee
            warning: null
            width: 100
        name: SEO
        uid: b25b9b63-a1b0-4ad9-9d11-29857442047c
handle: pages
hasTitleField: true
name: Pages
section: 45b7c78f-587d-441b-bbd1-605ca629d0bd # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
