fieldLayouts:
  800c29b7-0814-49b8-be52-d9a68e29e533:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1f5bf32c-4170-4102-b928-77ffb56bda0c
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ae28784-3a49-4473-bc88-69babb3acc0e
            warning: null
            width: 100
        name: Content
        uid: 6265bc60-a06c-4edc-bd77-f78dc7c00bc7
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c631964-c418-44b9-a438-4a13d5d1ac1e
            warning: null
            width: 100
        name: SEO
        uid: 318e690b-268b-4177-8a28-c11feabd5d2e
handle: profile
hasTitleField: true
name: Profile
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
