fieldLayouts:
  095aefa0-8c6b-4f90-abb7-9dfc35fec021:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc8275f3-459d-4abd-b825-70d7e90f6c7f
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ea31841-91fc-40c0-b281-10ccdefeb5ca
            warning: null
            width: 100
        name: Content
        uid: ac68430b-b330-4513-92e0-c1de15a8aa5a
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58a9e0f1-d782-4c50-a079-3128e8c42c62
            warning: null
            width: 100
        name: SEO
        uid: 9e229d08-1f55-4460-8abb-0a99a8b8cad0
handle: registrationCompleted
hasTitleField: true
name: 'Registration completed'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
