fieldLayouts:
  f19d5dc1-28c4-44f3-83e8-5f6e0d2ed056:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5d4e80c5-5c93-4f61-8005-7c896c65a1d0
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c489714-fc35-4d42-9f04-05e0466a5ee8
            warning: null
            width: 100
        name: Content
        uid: 3b85ef6e-5878-43dc-9013-5b4751b7c28c
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4314c02-992e-40f0-b8d0-39f3192d6945
            warning: null
            width: 100
        name: SEO
        uid: 7daf2f15-a33d-492e-a3b6-2c5bf633579f
handle: register
hasTitleField: true
name: Register
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
