color: null
fieldLayouts:
  86d679f2-c66c-4cad-a0cc-63b8753b55a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7b60618d-d9d5-41c4-ade2-d51291d7496a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e9cb47a-530d-4aa9-a98f-5049e6d0eb9e
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2d30acc-f77c-4758-b7ea-eb9ae78c344c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d8d1d5d4-1fab-4aaa-b9e7-0eca37062865
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49decd66-c2e9-416c-83cd-46bc0474a15e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c87ed224-8384-4f52-b68e-25ee0f423d52 # Contentbuilder CTA (Double)
            handle: cta
            includeInCards: false
            instructions: null
            label: 'Call to action'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce11868c-4ce8-4e9c-8a7c-4776531b3000
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2561c4fb-34b5-49e6-ade6-f774411e48ba
            handle: video
            includeInCards: false
            instructions: null
            label: Video
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3b691ab-3aba-42aa-9b69-08b6498a0827
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 896816a1-5444-4e1b-b74c-efbac472953c
            handle: placeholderImage
            includeInCards: false
            instructions: null
            label: 'Placeholder Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ada65645-8cc4-4f63-a6cf-2c60df1e7396
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c8533e19-1c6c-4d33-8e50-71babb409313
            handle: null
            includeInCards: false
            instructions: null
            label: 'Video position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2607da7f-daf5-4c42-8c89-915abc68dd03
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 561b6d99-0213-4cfc-bd14-c3c4f4ff02d3
            handle: videoCaption
            includeInCards: false
            instructions: null
            label: 'Video Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c6bd8fe-1653-466a-b821-71b168ce970f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f3f6d3ea-ccb1-48a5-bb33-93e1e31aff24
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95f06a3a-c17c-4032-abd6-82d452ed5e7b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dba25c67-8336-4776-bb85-63e3fffb4f1e
        userCondition: null
handle: textVideo
hasTitleField: false
icon: ''
name: 'Text + Video'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
