color: null
fieldLayouts:
  8e0153f8-35f6-4a49-bc77-316bc5dce081:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c32072f9-8c47-4064-8879-3ee67c000d42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 24983cba-9d55-413d-80dc-0374abd19ec0
            handle: null
            includeInCards: false
            instructions: null
            label: 'Title Column 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1e3e29f-0360-4cf5-9e9c-185e52b35ec3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1cd3558-d939-48d0-8628-239236ff699c
            handle: null
            includeInCards: true
            instructions: null
            label: 'Text Column 1'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8066edd1-fae1-4876-b905-cecb2c112d8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17647a4e-555f-49c4-ac53-e0a1ea9e5b40 # Contentbuilder CTA (Single)
            handle: ctaColumn1
            includeInCards: false
            instructions: null
            label: 'CTA Column 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe530c0a-ffbc-4943-8224-4d6a1796c8eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e73dd38a-5d76-40ba-99eb-25ee65bf7ab5
            handle: null
            includeInCards: false
            instructions: null
            label: 'Title Column 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12b922f4-dd7e-425b-a3ba-137fc623d829
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2d7684e-6737-4123-ad14-2c4e4221bbdd
            handle: null
            includeInCards: false
            instructions: null
            label: 'Text Column 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59368b27-46f3-4c5b-93b7-9e5bf5641ce9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17647a4e-555f-49c4-ac53-e0a1ea9e5b40 # Contentbuilder CTA (Single)
            handle: ctaColumn2
            includeInCards: false
            instructions: null
            label: 'CTA Column 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc1d6eae-85d2-47f2-a6c1-2e590fd4c115
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e5318bd-23e0-4319-8f7c-3f38350d8764
            handle: null
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c08b825-8341-4ca0-a415-67be5bbd04ae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a9d5fcb-7371-45df-b9f8-0a603830f3a3
        userCondition: null
handle: textTwoColumns
hasTitleField: false
icon: ''
name: 'Text (2 columns)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
