color: null
fieldLayouts:
  f4023492-353e-4a86-9695-455793644dc4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 69e397e5-732d-4e21-8924-bc5b3943f7dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Contentbuilder Title (Anchor)
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc671e99-b18e-4bf8-87ad-2be57587de6d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a25500cb-7c0d-474d-8ee0-757e3d200063 # Text - Contentbuilder Body Extended
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27ef5ef9-5e24-49b1-a0b2-cf30f86d4ff7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c87ed224-8384-4f52-b68e-25ee0f423d52 # Contentbuilder CTA (Double)
            handle: cta
            includeInCards: false
            instructions: null
            label: 'Call to action'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d051ae6-caac-471e-a524-898370a94f26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f21594e6-d83e-4047-a36c-0d6b709719e1
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed69e655-73d9-4f2b-94a0-2275e9b4faf8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: f21594e6-d83e-4047-a36c-0d6b709719e1
                  layoutElementUid: ed69e655-73d9-4f2b-94a0-2275e9b4faf8
                  operator: notempty
                  uid: c2224280-ea57-47d0-a10a-4983e61fa2df
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 40e14f90-0640-452d-9c8a-9f30f73bacbb
            handle: position
            includeInCards: false
            instructions: null
            label: 'Image position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e11cb59-1985-4f62-8da1-4c8694b813fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Content Builder  Background Color
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 872eeeca-445c-4f8f-a3f9-6ef0c2e3af98
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3cac461-fd7a-4f9a-8486-520f99041b3f
        userCondition: null
handle: textImage
hasTitleField: false
icon: ''
name: 'Text (+ Image)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
