color: null
fieldLayouts:
  4bb37325-4657-4b4b-a37d-a9601263cf72:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eddc6813-b8b9-40b5-b2c5-d1c6d9582399
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d66ffcef-8ccc-4e89-9e36-bce49e0dd17a
            handle: null
            includeInCards: true
            instructions: null
            label: Video
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10b5c1ef-5a1d-4b4f-90ca-41388b1bc2d1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: d66ffcef-8ccc-4e89-9e36-bce49e0dd17a
                  layoutElementUid: 10b5c1ef-5a1d-4b4f-90ca-41388b1bc2d1
                  operator: notempty
                  uid: c9cda17a-3637-4be7-a3d3-9427115ec4d1
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 724561c2-845a-427f-b005-e0c2a35e0112
            handle: null
            includeInCards: false
            instructions: null
            label: 'Placeholder Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b84cf6f5-a37f-4a41-8908-4157a510c99d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: d66ffcef-8ccc-4e89-9e36-bce49e0dd17a
                  layoutElementUid: 10b5c1ef-5a1d-4b4f-90ca-41388b1bc2d1
                  operator: notempty
                  uid: 3747b4a3-3f80-496a-b5b9-4078bd7d1195
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Content Builder  Background Color
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e587b459-84d1-48e7-bc62-527eb0dd6923
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: d66ffcef-8ccc-4e89-9e36-bce49e0dd17a
                  layoutElementUid: 10b5c1ef-5a1d-4b4f-90ca-41388b1bc2d1
                  operator: notempty
                  uid: 4e935a12-f840-41bf-9a35-c1c8c3c3912f
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: d364a1b7-6f05-47e2-a5b3-e9f38308473c # Text - Caption Text
            handle: videoCaption
            includeInCards: false
            instructions: null
            label: 'Video Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb3b53a4-0354-4198-909f-446c11150345
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1b44f4cf-c6f3-495e-b01a-3cb36749abfd
        userCondition: null
handle: video
hasTitleField: false
icon: ''
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
