headingLevels:
  - 3
  - 4
  - 5
name: Extended
options:
  code:
    indentSequence: '  '
  list:
    properties:
      reversed: true
      startIndex: true
      styles: false
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - bulletedList
  - numberedList
  - link
