fieldLayouts:
  7ca09cb5-dfea-4173-a601-1bcf64692d26:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: default
name: Default
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    hasUrls: false
    template: null
    uriFormat: null
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    hasUrls: false
    template: null
    uriFormat: null
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 3
  uid: 78b2b49c-eecb-4537-a468-a35be85a7b1c
