columnSuffix: null
handle: backgroundColor6
instructions: 'Select the background color of the whole section.'
name: 'Content Builder - Video - Background Color'
searchable: false
settings:
  dataSet: 'Background colors'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
