columnSuffix: null
handle: backgroundColor4
instructions: 'Select the background color of the whole section.'
name: 'Content Builder - Image - Background Color'
searchable: false
settings:
  dataSet: 'Background colors'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
