columnSuffix: null
handle: backgroundColor8
instructions: 'Select the background color of the whole section. Note: depending on the background color, the text colors might change.'
name: 'Content Builder - Text (+ Image) - Background Color'
searchable: false
settings:
  dataSet: 'Background colors'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
