columnSuffix: null
handle: blockTitle2
instructions: 'Add an optional title to the block'
name: 'Content Builder - Overview - Title'
searchable: true
settings:
  someAttribute: null
translationKeyFormat: null
translationMethod: site
type: modules\statik\fields\AnchorLink
