columnSuffix: null
handle: blockTitle3
instructions: 'Add an optional title to the block'
name: 'Content Builder - Text + Video - Title'
searchable: true
settings:
  someAttribute: null
translationKeyFormat: null
translationMethod: site
type: modules\statik\fields\AnchorLink
