columnSuffix: null
handle: blockTitle
instructions: null
name: 'Content Builder - Call To Action - Title'
searchable: true
settings:
  someAttribute: null
translationKeyFormat: null
translationMethod: site
type: modules\statik\fields\AnchorLink
