columnSuffix: null
handle: blockTitle5
instructions: null
name: 'Content Builder - Custom Table - Title'
searchable: true
settings:
  someAttribute: null
translationKeyFormat: null
translationMethod: site
type: modules\statik\fields\AnchorLink
