columnSuffix: null
handle: contentBuilderBackgroundColor
instructions: null
name: 'Content Builder  Background Color'
searchable: false
settings:
  dataSet: 'Background colors'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
