columnSuffix: null
handle: contentbuilderTitleAnchor
instructions: null
name: 'Contentbuilder Title (Anchor)'
searchable: true
settings:
  someAttribute: null
translationKeyFormat: null
translationMethod: site
type: modules\statik\fields\AnchorLink
