columnSuffix: qbmsdfrw
contentColumnType: string
fieldGroup: 815f235b-7817-462f-904d-a00904787aaf # Hyper
handle: ctaFieldLinkLayouts
instructions: null
name: 'Link Style'
searchable: false
settings:
  dataSet: 'CTA styles'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
