contentColumnType: string
fieldGroup: bfa2f99e-1c8c-4348-8f89-00708397a119 # Content
handle: hero
instructions: ''
name: Hero
searchable: true
settings:
  contentTable: '{{%stc_hero}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
