columnSuffix: null
contentColumnType: text
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: intro
instructions: 'Write a short and snappy text as an introduction to the content on the page. This will probably be displayed below the page title.'
name: 'Intro Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 131a4f6d-f00f-4238-b846-dd504bf669fe # Simple
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
