contentColumnType: text
fieldGroup: 61b9a78d-f3c0-4c99-8e91-d97e9768023c # Optimized Images
handle: optimizedContent
instructions: 'Optimized images for the content builder.'
name: 'Optimized Content'
searchable: true
settings:
  displayDominantColorPalette: ''
  displayLazyLoadPlaceholderImages: ''
  displayOptimizedImageVariants: ''
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - format
          - ''
        -
          - quality
          - '82'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - useAspectRatio
          - ''
        -
          - width
          - '1200'
    -
      __assoc__:
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - format
          - ''
        -
          - quality
          - '82'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - useAspectRatio
          - ''
        -
          - width
          - '820'
    -
      __assoc__:
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - format
          - ''
        -
          - quality
          - '82'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - useAspectRatio
          - ''
        -
          - width
          - '660'
    -
      __assoc__:
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - format
          - ''
        -
          - quality
          - '60'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - useAspectRatio
          - ''
        -
          - width
          - '375'
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
