contentColumnType: text
fieldGroup: 61b9a78d-f3c0-4c99-8e91-d97e9768023c # Optimized Images
handle: optimizedOverview
instructions: 'Optimized images for overview items.'
name: 'Optimized Overview'
searchable: true
settings:
  displayDominantColorPalette: ''
  displayLazyLoadPlaceholderImages: ''
  displayOptimizedImageVariants: ''
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - format
          - ''
        -
          - quality
          - '82'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - useAspectRatio
          - '1'
        -
          - width
          - '660'
    -
      __assoc__:
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - format
          - ''
        -
          - quality
          - '82'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - useAspectRatio
          - '1'
        -
          - width
          - '440'
    -
      __assoc__:
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - format
          - ''
        -
          - quality
          - '60'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - useAspectRatio
          - '1'
        -
          - width
          - '375'
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
