contentColumnType: text
fieldGroup: e9218327-8360-4a72-aae4-ff2db8be2c18
handle: overviewTitle
instructions: ''
name: 'Overview title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
