columnSuffix: null
handle: position2
instructions: 'Select the position of the image in relation to the text block.'
name: 'Content Builder - Text (+ Image) - Image position'
searchable: false
settings:
  default: left
  options:
    __assoc__:
      -
        - left
        - '1'
      -
        - center
        - ''
      -
        - right
        - '1'
      -
        - full
        - ''
      -
        - drop-left
        - ''
      -
        - drop-right
        - ''
translationKeyFormat: null
translationMethod: none
type: rias\positionfieldtype\fields\Position
