contentColumnType: text
fieldGroup: 29ce1a5b-53b3-4361-96e4-20fc58e90dac # SEO
handle: seo
instructions: ''
name: SEO
searchable: true
settings:
  allowSitenameDisable: ''
  allowSitenameOverwrite: ''
  tabs:
    __assoc__:
      -
        - general
        - '1'
      -
        - facebook
        - '1'
      -
        - twitter
        - '1'
translationKeyFormat: null
translationMethod: site
type: studioespresso\seofields\fields\SeoField
