columnSuffix: null
handle: titleColumn1
instructions: 'Add an optional title to the block'
name: 'Content Builder - Text (2 columns) - Title Column 1'
searchable: true
settings:
  someAttribute: null
translationKeyFormat: null
translationMethod: site
type: modules\statik\fields\AnchorLink
