contentColumnType: string(255)
fieldGroup: 39b3406d-d1bb-4a84-a13a-bce5cc293238
handle: youtube
instructions: ''
name: Youtube
searchable: true
settings:
  maxLength: 255
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
