dateModified: 1635853537
email:
  fromEmail: no-reply@mailer.today
  fromName: $SYSTEM_NAME
  replyToEmail: null
  template: _mail/_layout
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  config-values-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cookie-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cta:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  dumper:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  element-index-defaults:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      Asset:
        - filename
        - size
        - dateModified
      Category:
        - link
      Entry:
        - postDate
        - author
        - dateUpdated
        - revisionCreator
        - link
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: A5CFILCDC9CCY0XQEZSQ3JWL
    schemaVersion: 1.1.11
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: N1AW4QWHBOTNF5C2HCN14SLA
    schemaVersion: 1.0.0
  navigate:
    enabled: '1'
    licenseKey: R3CPY6ZNWPAN90GL1LU4ZVG8
    schemaVersion: 2.4.0
    settings:
      anyoneCanAdd: ''
      pluginLabel: Navigations
  position-fieldtype:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
  seo-fields:
    edition: standard
    enabled: true
    licenseKey: ISE7A0Q95UBOMAB3QAN1FX4V
    schemaVersion: 1.0.0
  super-table:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.2.1
    settings: null
  translate:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: Europe/Brussels
