field: 9faf6a00-afea-4a29-a217-e6af774f6b55
fieldLayouts:
  77473d9a-25e1-402f-a763-c6e3ff92bdbb:
    tabs:
      -
        fields:
          fc9b3c7f-00f8-4113-aa56-b2328011d192:
            required: '1'
            sortOrder: '1'
        name: Content
        sortOrder: '1'
fields:
  fc9b3c7f-00f8-4113-aa56-b2328011d192:
    contentColumnType: text
    fieldGroup: null
    handle: linkit
    instructions: ''
    name: Link
    searchable: '1'
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: ''
      typeSettings:
        asset:
          sources: '*'
        category:
          sources: '*'
        email:
          disableValidation: ''
        entry:
          sources: '*'
        tel:
          disableValidation: ''
        url:
          disableValidation: ''
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\cta\fields\CTAField
