field: 302aeb89-2e5c-42f2-a735-98e504b28a37
fieldLayouts:
  d85d743d-9445-4bbe-b507-717c93f5ba87:
    tabs:
      -
        fields:
          6d99d3e8-e687-44e6-9e4f-8724da1c5123:
            required: '1'
            sortOrder: '1'
        name: Content
        sortOrder: '1'
fields:
  6d99d3e8-e687-44e6-9e4f-8724da1c5123:
    contentColumnType: text
    fieldGroup: null
    handle: linkit
    instructions: ''
    name: Link
    searchable: '1'
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: ''
      typeSettings:
        asset:
          sources: '*'
        category:
          sources: '*'
        email:
          disableValidation: ''
        entry:
          sources: '*'
        tel:
          disableValidation: ''
        url:
          disableValidation: ''
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\cta\fields\CTAField
