field: ca8bb389-d0f3-4dbb-af40-e2f6ef211040
fieldLayouts:
  40a3aa8a-1e1f-460b-8130-33021783204b:
    tabs:
      -
        fields:
          97e1c649-ce58-4388-bbc1-1f4e41d938b6:
            required: '1'
            sortOrder: '1'
        name: Content
        sortOrder: '1'
fields:
  97e1c649-ce58-4388-bbc1-1f4e41d938b6:
    contentColumnType: text
    fieldGroup: null
    handle: linkit
    instructions: ''
    name: Link
    searchable: '1'
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: 'Read more'
      typeSettings:
        asset:
          sources: '*'
        category:
          sources: '*'
        email:
          disableValidation: ''
        entry:
          sources: '*'
        tel:
          disableValidation: ''
        url:
          disableValidation: ''
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\cta\fields\CTAField
