fieldLayouts:
  a646a8f4-7495-4add-979c-80f88cae05f0:
    tabs:
      -
        elements:
          -
            fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: fallback
name: Fallback
