fieldLayouts:
  95b592be-7c58-48f3-8fcd-eddbb3ec81da:
    tabs:
      -
        elements:
          -
            fieldUid: 6ca94949-c3f4-465d-88c7-3d4736d97ed4 # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 072209d1-1c68-4ee5-9a66-a209b518da6d # Mail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: e48813cd-24dc-4b06-a97d-2a95520dcc24 # Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Info
        sortOrder: 1
handle: generalInfo
name: 'General Info'
sortOrder: 2
