fieldLayouts:
  6f7fef0a-6de7-486f-887d-716ee0d2a256:
    tabs:
      -
        elements:
          -
            fieldUid: f694fce1-48ca-4bfe-9fba-196195547a36 # Facebook
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2e4b3bb0-26e4-47d2-9445-54401a221c63 # Twitter
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ce1fab3c-0b02-49d8-8d8f-1bab2d7c05e2 # LinkedIn
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9bc4b9f2-7fc6-48b0-a3df-8e9c061a70c6 # Instagram
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6221c006-75b9-4fa5-a352-4cd4317fb5d7 # Youtube
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Social links'
        sortOrder: 1
handle: socialMedia
name: 'Social Media'
