description: ''
handle: contentManagers
name: 'Content Managers'
permissions:
  - accessplugin-formie
  - accessplugin-freeform
  - accessplugin-navigate
  - accessplugin-translate
  - accesscp
  - registerusers
  - moderateusers
  - 'assignusergroup:3196b984-5af4-44dd-a6db-ac2c8f7924d9' # Content Managers
  - assignusergroups
  - administrateusers
  - editusers
  - 'editsite:6de046f0-6167-4af1-aa91-ffaf83e36a14' # NL
  - 'editsite:fd2014b7-5bc0-49a9-ac30-e009081532f7' # FR
  - 'editsite:e57cf13b-f9cb-484a-8093-a897fa43eb68' # EN
  - 'publishentries:5d236e94-b6a8-472c-9296-a5c992cdd49a'
  - 'publishpeerentrydrafts:5d236e94-b6a8-472c-9296-a5c992cdd49a'
  - 'deletepeerentrydrafts:5d236e94-b6a8-472c-9296-a5c992cdd49a'
  - 'editpeerentrydrafts:5d236e94-b6a8-472c-9296-a5c992cdd49a'
  - 'editentries:5d236e94-b6a8-472c-9296-a5c992cdd49a'
  - 'publishentries:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'publishpeerentrydrafts:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'deletepeerentrydrafts:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'editpeerentrydrafts:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'editentries:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
  - 'createentries:edafcdcc-cb6a-4636-8b06-692031d123dc'
  - 'publishentries:edafcdcc-cb6a-4636-8b06-692031d123dc'
  - 'publishpeerentries:edafcdcc-cb6a-4636-8b06-692031d123dc'
  - 'editpeerentries:edafcdcc-cb6a-4636-8b06-692031d123dc'
  - 'publishpeerentrydrafts:edafcdcc-cb6a-4636-8b06-692031d123dc'
  - 'editpeerentrydrafts:edafcdcc-cb6a-4636-8b06-692031d123dc'
  - 'editentries:edafcdcc-cb6a-4636-8b06-692031d123dc'
  - 'publishentries:5611e98d-93ec-4bd4-95dd-18f282b8c5e8'
  - 'publishpeerentrydrafts:5611e98d-93ec-4bd4-95dd-18f282b8c5e8'
  - 'deletepeerentrydrafts:5611e98d-93ec-4bd4-95dd-18f282b8c5e8'
  - 'editpeerentrydrafts:5611e98d-93ec-4bd4-95dd-18f282b8c5e8'
  - 'editentries:5611e98d-93ec-4bd4-95dd-18f282b8c5e8'
  - 'createentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'publishentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'deleteentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'publishpeerentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'deletepeerentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'editpeerentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'publishpeerentrydrafts:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'deletepeerentrydrafts:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'editpeerentrydrafts:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'editentries:c576870d-abd8-46aa-8fe5-cdd12c40dfa8'
  - 'publishentries:4c32edae-2824-4f0f-b38b-2477d2500dfe'
  - 'publishpeerentrydrafts:4c32edae-2824-4f0f-b38b-2477d2500dfe'
  - 'deletepeerentrydrafts:4c32edae-2824-4f0f-b38b-2477d2500dfe'
  - 'editpeerentrydrafts:4c32edae-2824-4f0f-b38b-2477d2500dfe'
  - 'editentries:4c32edae-2824-4f0f-b38b-2477d2500dfe'
  - 'createentries:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'publishentries:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'deleteentries:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'publishpeerentries:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'deletepeerentries:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'editpeerentries:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'publishpeerentrydrafts:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'deletepeerentrydrafts:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'editpeerentrydrafts:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'editentries:45b7c78f-587d-441b-bbd1-605ca629d0bd'
  - 'editglobalset:4666d048-0521-4d0f-9a4a-208e6182fb85'
  - 'editglobalset:10fdc148-c0a4-486b-a5d1-3d36f2862352'
  - 'editcategories:64516e7d-b46e-44ff-aa53-34e7e1e0a89d' # Default
  - 'saveassetinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'createfoldersinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'deletefilesandfoldersinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'replacefilesinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'editimagesinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'editpeerfilesinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'replacepeerfilesinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'deletepeerfilesinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'editpeerimagesinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'viewpeerfilesinvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - 'viewvolume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  - freeform-submissionsmanage
  - freeform-submissionsaccess
  - formie-createforms
  - formie-deleteforms
  - formie-editforms
  - formie-manageformbehavior
  - formie-managenotificationstemplates
  - formie-managenotifications
  - formie-manageforms
  - formie-editsubmissions
  - formie-viewsubmissions
  - formie-viewsentnotifications
