defaultPlacement: end
enableVersioning: true
entryTypes:
  - aac522be-8926-4b5e-ae63-cb77840a69c9 # Registration completed
handle: registrationCompleted
name: 'Registration completed'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_registrationCompleted.twig
    uriFormat: registratie-voltooid
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_registrationCompleted.twig
    uriFormat: registration-completed
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_registrationCompleted.twig
    uriFormat: inscription-terminee
type: single
