handle: statik
name: Statik
outputCssLayout: '1'
outputCssLocation: manual
outputCssTheme: ''
outputJsBase: '1'
outputJsLocation: page-footer
outputJsTheme: ''
sortOrder: 99
template: _formie
useCustomTemplates: '1'
