handle: statik
name: Statik
outputCssLayout: '1'
outputCssLocation: page-header
outputCssTheme: ''
outputJsBase: '1'
outputJsLocation: page-footer
outputJsTheme: '1'
sortOrder: 99
template: ''
useCustomTemplates: ''
