name: SSH deploy on push
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PORT: ${{ secrets.PORT }}
          with:
            source: "*/*.*"
            target: ${{ secrect.SUB_DIR ))