name: SSH deploy on push
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh key
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: ${{ secrets.SUB_DIR }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.KEY }}